[theme]
primaryColor = "#00B5B8"  # Teal blue (Fitbit's brand color)
backgroundColor = "#E0E7EC"  # Light grey background
secondaryBackgroundColor = "#b0a599"  # Slightly darker for content containers
textColor = "#1C1C1C"  # Dark grey/black for contrast
